### PR TITLE
update to new purescript-argonaut-codecs -> typed decoder errors

### PR DESCRIPTION
**Pull request by srghma**
## What does this pull request do?

updates to https://github.com/purescript-contrib/purescript-argonaut-codecs/commit/2ad2147e292a51cccfa6abcf8017f17c1367a82c

### CODE REVIEW

**Comment by thomashoneyman** [comment]
You’ll need to update dependencies in the Bower file; I would prefer to handle the Spago migration on my own — please keep this PR to just the argonaut-codecs change. Thanks!

**Comment by srghma** [comment]
removed spago, but dont know how to update bower. Could you please to that for me

**Comment by thomashoneyman** [comment]
@srghma For any project where you want to update their code to use the new Argonaut I would recommend:

1. Update the Bower code to point at v7.0.0 of argonaut-codecs, if they use codecs, and if they use argonaut wait for that PR to be merged and that library to update before moving forward.
2. Update the spago.dhall file the same way -- point to v7.0.0 of argonaut-codecs, if they use codecs, or wait for the argonaut PR to be made before updating.
3. Update the code making the minimum of changes necessary to update to typed errors, trying not to change anything unrelated to the typed errors (including migrating to Spago or refactoring any code)

That way the library maintainers have a simple, straightforward PR they can review and merge. When additional changes are made it makes it unlikely that the library maintainer will be able to review and merge your PR.

You will need to update the dependencies in the Bower files / Spago files on behalf of the library maintainers as part of your update -- you can just do this by manually editing the files.

For Bower, manually change the version of the `purescript-argonaut-codecs` dependency to v7.0.0, and then run `bower install` to make sure that the version is compatible with the other versions of their libraries they're using (it should be).

For Spago, manually add an `override` key that sets the `purescript-argonaut-codecs` version to `v7.0.0`. You can see an example of how to add overrides in the Spago readme.

**Comment by thomashoneyman** [comment]
I would focus only on getting the Argonaut / Argonaut Codecs / Argonaut Traversals / Argonaut Generics libraries updated first before opening pull requests on any other libraries just so that the base layer is taken care of.

**Comment by thomashoneyman** [comment]
Updated and the [new release is live](https://github.com/thomashoneyman/purescript-slug/releases/tag/v2.0.0). Thanks!

**Pull request closed without merging**
